### PR TITLE
Fix c sharp tests

### PR DESCRIPTION
**Pull request by Andersoft**
This PR fixes the following

- The response from https://cscc-gl.herokuapp.com/ does not deserialize into `TestCaseList` but will deserialize into `JsonConvert.DeserializeObject<List<TestCase>>(responseBody)`.

- Tests are also not picked up by visual studio

- `Q1Object` has the wrong property types `int` but the data being return is a `decimal` so it fails deserialization. IMO these should be `decimals` also `Question1` should also take `decimals` as its arguments.

- Test methods are `async void` which is fire and forget, the program wont wait for the test method to complete AFAIK meaning scores may not be posted.

- Changes tests attributes to NUnit instead of MSTest

- Changes the project type of the challenge to be a library instead of a web application

- Splits the project structure  into `src` & `test` folders for improved maintainability

- Removes `.vs`, `bin` & `obj` folders as these are all build artifacts and meta data that should not be included in source control

### CODE REVIEW

**Comment by EmanueleFWM** [comment]
Did you also manage to get this working for their remote judging?
I tried your version and the tests work fine locally, but my scores do not get updated after commiting to the github repository.

**Comment by Supercide** [comment]
I wasn't able to get the scores to update, i reckon this is failing to build on travis. I don't have access to their travis server to see whats up with it but i could probably figure it out. If i have some time tonight i will see if i can fix it. I am Andersoft btw

**Comment by EmanueleFWM** [comment]
Hmm ok, I wasn't able to get the judging working with their original code either so I wasn't sure if something was wrong with their setup or if it was because I had already submitted in a different language.
By the way, thanks a lot for fixing this up!

**Comment by Kairain** [comment]
Does anyone know how start, end strings are passed in Question 6? I cannot get this working as well.

**Comment by madhur4127** [comment]
Sorry, If it sounds dumb but does the scoreboard update after applying this patch?

**Comment by Supercide** [comment]
i have not been able to get the scoreboard to update on my version or there's, however i haven't tried there new fix they pushed out yesterday. Might be worth raising  ticket via the credit site, they don't seem to respond to Issues raised on here ☹

**Comment by madhur4127** [comment]
I am testing out new patch and it seems test are running but I cannot see the console output to check whether the solution is correct/incorrect. It only says that some tests were run:

```
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
  √ TestQ1 [1s 965ms]                                                                                                               
  √ TestQ2 [328ms]                                                                                                                  
  √ TestQ3 [616ms]                                                                                                                  
  √ TestQ4 [339ms]                                                                                                                  
  √ TestQ5 [327ms]                                                                                                                  
  √ TestQ6 [322ms]                                                                                                                                   
Test Run Successful.
Total tests: 6
     Passed: 6
 Total time: 5.8717 Seconds
```

Do you have any idea on how to enable console output. I tried changing the verbosity level from `--verbosity=minimal` to `--verbosity=diagostic` but still I am unable to see the console output.

Looks like this is an active issue.

**Comment by Supercide** [comment]
I don't think they have put assertions in the test so they will look like they have all passed. you can put an assertion at the end of each test to report the pass or fail and maybe a % of how many scenarios you got correct.

**Comment by Supercide** [comment]
yeah it needs assert multiple adding to get that level of information. im not sure how to do it in mstest (what they are using) but you can do this easily via nunit

**Pull request closed without merging**
