### PR TITLE
Question1

### PR DESCRIPTION
**Pull request by adesewa12**
@CS-CodingChallenge

### CODE REVIEW

**Comment by fo0s** [comment]
Please don't push your code here, it's a public repo and everyone is seeing it.
Instead please push to the private repo where you cloned from.

**Comment by adesewa12** [comment]
> Please don't push your code here, it's a public repo and everyone is seeing it.
> Instead please push to the private repo where you cloned from.

is there a way for me to delete it

**Comment by adesewa12** [comment]
How do I delete it

**Comment by fo0s** [comment]
https://help.github.com/en/articles/closing-a-pull-request

**Pull request closed without merging**
